version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=tm-teste
      - POSTGRESQL_PASSWORD=tm-teste
      - POSTGRESQL_DATABASE=taskManager
